// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "html/template"

func Page(content template.HTML) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>LaTeX Markdown Preview</title><link rel=\"stylesheet\" href=\"https://latex.now.sh/style.css\"><script>\n\t\t\t\tMathJax = {\n\t\t\t\t\ttex: {\n\t\t\t\t\t\tinlineMath: [['$', '$'], ['\\\\(', '\\\\)']],\n\t\t\t\t\t\tdisplayMath: [['$$', '$$'], ['\\\\[', '\\\\]']],\n\t\t\t\t\t\tprocessEscapes: true\n\t\t\t\t\t}\n\t\t\t\t};\n\t\t\t</script><script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script><style>\n\t\t\t\t/* PDF viewer shell */\n\t\t\t\thtml, body {\n\t\t\t\t\tmargin: 0;\n\t\t\t\t\tpadding: 0;\n\t\t\t\t\tbackground: #404040;\n\t\t\t\t\tmin-height: 100vh;\n\t\t\t\t}\n\n\t\t\t\t/* Override latex.css body defaults */\n\t\t\t\tbody.libertinus {\n\t\t\t\t\tmax-width: none;\n\t\t\t\t\tpadding: 2.5rem 0;\n\t\t\t\t\tdisplay: flex;\n\t\t\t\t\tflex-direction: column;\n\t\t\t\t\talign-items: center;\n\t\t\t\t}\n\n\t\t\t\t/* A4 page card */\n\t\t\t\tmain {\n\t\t\t\t\tbackground: #fff;\n\t\t\t\t\twidth: 210mm;\n\t\t\t\t\tmin-height: 297mm;\n\t\t\t\t\tpadding: 25mm 20mm;\n\t\t\t\t\tbox-sizing: border-box;\n\t\t\t\t\tbox-shadow: 0 4px 20px rgba(0,0,0,0.5), 0 1px 4px rgba(0,0,0,0.3);\n\t\t\t\t\tmargin: 0 auto;\n\t\t\t\t\t/* keep latex.css font size sane */\n\t\t\t\t\tfont-size: 11pt;\n\t\t\t\t\tline-height: 1.6;\n\t\t\t\t}\n\n\t\t\t\t/* Page break simulation between multiple \"pages\" when content overflows */\n\t\t\t\t@media screen {\n\t\t\t\t\tmain {\n\t\t\t\t\t\tborder: 1px solid #222;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t</style></head><body class=\"libertinus\"><main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(string(content)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</main><script>\n\t\t\t\tconst ws = new WebSocket(\"ws://\" + window.location.host + \"/ws\");\n\t\t\t\tws.onmessage = function(event) {\n\t\t\t\t\tif (event.data === \"reload\") {\n\t\t\t\t\t\twindow.location.reload();\n\t\t\t\t\t}\n\t\t\t\t};\n\t\t\t\tws.onclose = function() {\n\t\t\t\t\tconsole.log(\"Connection closed. Reconnecting...\");\n\t\t\t\t\tsetTimeout(() => window.location.reload(), 2000);\n\t\t\t\t};\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
